### ISSUE TITLE
[Question] Name reusable blocks?

### ISSUE THREAD

**Issue by lonix1** [garciaalvaro/block-navigation#1]
*Firstly, this plugin is awesome - well done!*

All reusable blocks are shown as "Reusable Block". Which makes editing a long document quite difficult.

Is there a way to name those blocks?

**Comment by garciaalvaro** [comment]
Hi @lonix1, thanks for the nice comment and for letting me know!

I just commited a change that adds the Reusable Block's title. So now inside the Block List these block types can be identified more easily.

I need to do some tests to confirm things work correctly, and if so I will publish a new version with the change in the beginning of next week.

I'll let you know once its released.

Thanks!

**Comment by lonix1** [comment]
Thanks I look forward to being the first beta tester! :)

**Comment by garciaalvaro** [comment]
I made a beta release. If you want to take a look at it, the .zip can be downloaded here: https://github.com/garciaalvaro/block-navigation/releases/download/1.3.0-beta/block-navigation-1.3.0-beta.zip

Reusable blocks now show their title. The only issue is when creating a new one inside the editor, until the page is reloaded it won't get the updated title. I might leave this issue for a future release though, as I couldn't find a way to get that value from the store.

**Comment by lonix1** [comment]
Thanks! Works very nicely! And I don't think the refreshing issue is a concern...

Now the plugin is even easier to use than the built-in outline popup. 👍
