### ISSUE TITLE
Fix Icon sizing

### ISSUE THREAD

**Issue by tounano** [garciaalvaro/block-navigation#10]
hey @garciaalvaro ,

Sometimes block creators have larger icons than usual.

![image](https://user-images.githubusercontent.com/5513418/129448614-6ae344f4-3ab6-4e89-8fdf-69bde9b1c9a0.png)

It would be a good idea to enforce the icon size via CSS.

Thanks.

**Comment by garciaalvaro** [comment]
You are right, the icon size should be set in the CSS.
Will fix it a soon as I can.
Thanks for letting me know.

**Comment by garciaalvaro** [comment]
This issue has been fixed in the latest release (4.0.1).
