### ISSUE TITLE
[Question] Maintain tree's state

### ISSUE THREAD

**Issue by lonix1** [garciaalvaro/block-navigation#2]
Do you know whether it's possible (via javascript or otherwise) to maintain the tree's state? Otherwise it automatically expands, so you lose your place and need to scroll to find the correct node again.

Maybe there's a way to force it to save its state?

**Comment by garciaalvaro** [comment]
What do you mean by the tree state? When does it automatically expand? Thanks

**Comment by lonix1** [comment]
I mean the tree structure shown in the navigation panel.

- let's say you open the "Block Navigation" panel
- you collapse some nodes, expand others
- then you switch to a different panel, e.g. "Settings"
- then you switch back to the "Block Navigation" panel

Result: it will be automatically expanded so all nodes in the tree are shown. Anything you collapsed/expanded before will now be expanded.

So the panel doesn't "remember" the tree's state. In fairness, the built-in document navigator also has this behavior.

I was hoping there is a way to force it to remember the state. Maybe not... 😢 

Hopefully if I find something I will post back here with an update!

**Comment by garciaalvaro** [comment]
I made some changes to achieve this. It used to be possible but in a latest refactor I approached it in a different way. I'll update it and let you know.

**Comment by garciaalvaro** [comment]
I commited the new changes which can be downloaded here:
https://github.com/garciaalvaro/block-navigation/releases/download/1.3.0-beta.2/block-navigation-1.3.0-beta.2.zip

It should now work as you commented, keeping the state when closing the plugin sidebar.

**Comment by lonix1** [comment]
Amazing, another important feature! There is no need anymore to use the built-in navigation popup, this one is more useful.

How long does it take for the plugin to appear on the wordpress site?

**Comment by garciaalvaro** [comment]
As soon as the developer uploads the files, the repository page shows the new version almost instantly.

I already published version 1.3.0, so it should be ready to use!

**Comment by lonix1** [comment]
This was the best update yet. It's great!
