### ISSUE TITLE
[Feature Request] Auto select and scroll to current block

### ISSUE THREAD

**Issue by lonix1** [garciaalvaro/block-navigation#3]
@garciaalvaro I hope you don't mind if I flood you with even more ideas... I think this plugin is so useful I can't help but think of ways to make it better. Please ignore or delete if I'm bugging you! 😃 

Another idea:

Would be very useful if when you click on some block in the editor, and IF the navigation panel is visible, then it would automatically select that block in the tree and scroll to it.

This would probably be more complicated than all the other stuff you've done because the plugin needs to communicate somehow with the main editor? Well it's just an idea, not sure if it's possible, but would be really cool.

**Comment by garciaalvaro** [comment]
I'm glad you find it useful :)

Currently when an element is selected in the editor it will be selected in the sidebar, and viceversa.

Scroll to the selected element functionality sounds good. I just added it, you can find it in the develop branch. I will wait to see if there are other fixes or modifications to be made before releasing a new version, though. But let me know if you need it and I'll do a beta release.

Thanks for the suggestion

**Comment by lonix1** [comment]
Awesome!
