### ISSUE TITLE
[Question] How to move block into group block?

### ISSUE THREAD

**Issue by lonix1** [garciaalvaro/block-navigation#4]
Suppose a group block already contains items. If I want to move some other block into the group, then I can.

But suppose a group block is empty. If I want to move some block into the group, I cannot. I first need to create a dummy block inside the group, then move my block into the group, then delete the dummy block.

Is there an easier way to do this that I don't know about?

**Comment by garciaalvaro** [comment]
You are right, that is the current behavior, which certainly needs to be improved.

It's the next thing in my to-do list. I'll let you know once I can look into it and have some advance.

**Comment by garciaalvaro** [comment]
Just added a commit that includes this functionality. I am planning to make a release next week which will include this and other changes. Closing this for now. Thanks!

**Comment by lonix1** [comment]
Thanks!

**Comment by garciaalvaro** [comment]
This functionality is now released with other updates, the new version is 2.0.0.
Sorry for the delay, last weeks have been busy.

**Comment by lonix1** [comment]
😀
