### ISSUE TITLE
Display Variation Name instead of Block Name

### ISSUE THREAD

**Issue by tounano** [garciaalvaro/block-navigation#9]
Hey @garciaalvaro ,

I think it would be better to display the Variation Name instead of the Block Name. In 90% of the cases it would result in the same string.

Here's where it would defer:
If you add a YouTube Embed block and a Twitter Embed block they both would show as "Embed" with the Embed icon. It is possible however to display the name of the variation instead of the block.

Here's what I think will solve this:
Here:
https://github.com/garciaalvaro/block-navigation/blob/136fb42d26af83e5471bce01517f0aaf9a488eaf/src/components/Block/Container/Header/Title/Title.tsx

Instead of fetching the Block Name, it's possible to use `useBlockDisplayInformation` as documented here:
https://github.com/WordPress/gutenberg/blob/086b77ed409a70a6c6a6e74dee704851eff812f2/packages/block-editor/src/components/use-block-display-information/README.md

You can get both the variation name and the icon by using this function.

Would you like me to implement it and issue a pull request?

**Comment by garciaalvaro** [comment]
Hi @tounano,

Thank you for your suggestion, showing the variant in certain blocks such as the Embed block could be very useful.
I have been working on a new version of the plugin for some days, and today I could implement this feature checking the hook you commented (commits [1](https://github.com/garciaalvaro/block-navigation/commit/94c4617f6bfc825d6057addcee77a132114aa7ef) and [2](https://github.com/garciaalvaro/block-navigation/commit/918d1476f715c34c98b12b0c525ed069c18369d9)). Hopefully the new version can be released soon.

Thank you again for the suggestion.

**Comment by tounano** [comment]
Awesome @garciaalvaro great work :)

Let me know if you need more help with implementing this. I love your plugin :)

**Comment by garciaalvaro** [comment]
The latest version (4.0.0) has been released and includes the mentioned commits.
Thank you :)
